name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build and deploy
        run: |
#          eas build --platform all --non-interactive --no-wait
#          eas deploy --platform all --non-interactive
          npx expo export --platform=web
          eas deploy --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }} 
